### PR TITLE
[WIP] Added tests for jupyter-js-output-area

### LINKED ISSUE #5: Tests
We need to add tests, likely adopting `mocha` again.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #5.

Opening up a WIP PR for this.

Let me know what things you want covered with tests.

cc/ @rgbkrk @jdfreder

### CODE REVIEW

**Comment by rgbkrk** [comment]
This definitely gets us off to the right foot. I think we can at least merge package.json changes and add a `.travis.yml`. These tests target part of the interface itself, so that's fine. The banana test isn't doing too much since it's basically testing the fact that it has an array underneath.

**Comment by captainsafia** [comment]
I assume you will be taking care of the Travis set up?

> The banana test isn't doing too much since it's basically testing the fact that it has an array underneath.

Trust but verify!

bgnbp

**Comment by rgbkrk** [comment]
That cat picture is very apropos.

What I'm saying is that the unit tests should go after functions. The test on `_state` tests that the internal structure is an array with array properties. It's basically testing (correctly) that we're consistently using an array for `_state` and that JavaScript's `Array` behaves like an `Array` (effectively testing that JS works). A simplified version of that test would be `Array.isArray(this._state)`. Which, at that point you'd want to tear that test out.

Instead test `model.state` which does operations on top of that internal data structure.

**Comment by captainsafia** [comment]
Ah. OK. Thanks for the clarification that makes a lot of sense.

I'll replace the current test with one that tests getter/setter and commit
the other tests I made as soon as I'm on solid ground for more than 16
hours!

_insert picture of jet lagged kitten here because I ran out of free
Internet minutes_ :'(

**Comment by rgbkrk** [comment]
Just a note that you can use `_state` to verify operations run on `state`, as part of your unit testing.

**Comment by jdfreder** [comment]
This is great!  Thanks for working on this @captainsafia !

**Comment by captainsafia** [comment]
kitten15

**Comment by captainsafia** [comment]
@rgbkrk — to what extent should `jupyter-js-output-area` be dealing with messy data?

**Comment by rgbkrk** [comment]
> to what extent should jupyter-js-output-area be dealing with messy data?

Messages should conform to the message spec. If it doesn't have the right fields, we should report that error appropriately (there's like 0 interface for that right now). Setting state should conform to whatever subset of nbformat/display_data we're handling (ask @jdfreder).

**Comment by captainsafia** [comment]
Will be opening up another PR alongside this to deal with messy data.

**Comment by rgbkrk** [comment]
:smile:

**Comment by rgbkrk** [comment]
Want to add a Travis YML too?

**Comment by captainsafia** [comment]
Yeah! I was actually about to ask about that.

Will collaborator permissions on the repo allow me to set that up?

**Comment by captainsafia** [comment]
@rgbkrk — Do you think you can take a look and let me know if my testing approach is alright?

If so, I'm thinking we can merge this (mostly for the Travis README badge) and I'll just write the tests for the data validation alongside the PR like a normal person.

**Comment by rgbkrk** [comment]
Look at that green check mark!

**Comment by rgbkrk** [comment]
Heh, didn't remove the `[WIP]` tag. We're now on the wall of shame.

**Comment by captainsafia** [comment]
WIP now stands for Work Is Perfect.

**Pull request merged**
