### PR TITLE
Fix demo with Node http-server

### PR DESCRIPTION
**Pull request by captainsafia**

### CODE REVIEW

**Comment by rgbkrk** [comment]
:boom: thank you, checking it out now

**Comment by rgbkrk** [comment]
`npm install && npm run dev` appears to work like a champ!

I'm not sure why the tracebacks aren't coming up right though:

screenshot 2015-08-29 17 29 53

**Comment by rgbkrk** [comment]
As is, this looks great and does what it needs. I'll address the traceback now.

**Comment by captainsafia** [comment]
:+1:  Thanks for looking into the tracebacks, @rgbkrk!
giphy-3

**Comment by rgbkrk** [comment]
That is... That is... wow.

**Pull request merged**
